### ISSUE TITLE
Keep rst code along with py code in the same files.

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/python-prakriya#16]
Ideally documentation source should always lie with the code. That way, the chances of documentation and code diverging is minimized. All this involves is copy pasting https://github.com/drdhaval2785/python-prakriya/blob/master/docs/usage.rst to appropriate places within the code. You can see https://github.com/vedavaapi/sanskrit_data/tree/master/docs for an example.

PS @avinashvarna - you may like to follow this repo as well.

**Comment by vvasuki** [comment]
@drdhaval2785 plz add me to the contributor list as well so I can reopen issues etc.. as needed.

**Comment by drdhaval2785** [comment]
Sure. It is in my mind. The code docstring was copied to usage.rst. But as the code kept on changing, currently they have diverged. The documentation and docstring will be brought to same level soon. And as regards the structure of project, this is default cookiecutter template. I have not changed much. Cookiecutter helped integrating with tox, travis, readthedocs, pip painless.

**Comment by drdhaval2785** [comment]
Made them identical.

**Comment by vvasuki** [comment]
`usage.rst` is still not referring to and using docstrings embedded with the code - so you still have a duplication problem?

**Comment by drdhaval2785** [comment]
Now the usage.rst is reading directly from code.
