### ISSUE TITLE
Question: Can we get karmaNi forms?

### ISSUE THREAD

**Issue by aniruddha753** [drdhaval2785/python-prakriya#59]
Sorry for posting a question in the Issues section. (I didnt find any other way to ask).
Is it possible to get the karmaNi forms using this package? From the arguments, I feel it is not supported. Just wanted to confirm.

Thanks
Aniruddha

**Comment by drdhaval2785** [comment]
vidyut-prakrita handles this.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0001
select karmaNi.
