### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by PaawanSharma** [drdhaval2785/python-prakriya#94]
* prakriya version: 0.2.1
* Python version: 3.7.3
* Operating System: macOS Catalina 10.15.5

### Description

I am getting this error.

### What I Did

```
>>> from prakriya import Prakriya
>>> p = Prakriya()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paawansharma/anaconda3/lib/python3.7/site-packages/prakriya-0.2.1-py3.7.egg/prakriya/verbforms.py", line 127, in __init__
    self.appdir = app_dir('prakriya')
  File "/Users/paawansharma/anaconda3/lib/python3.7/site-packages/prakriya-0.2.1-py3.7.egg/prakriya/utils.py", line 32, in app_dir
    from AppKit import NSSearchPathForDirectoriesInDomains as searchin
ModuleNotFoundError: No module named 'AppKit'
```

**Comment by drdhaval2785** [comment]
While googling, I found the following solution.

sudo pip install pyobjc

**Comment by drdhaval2785** [comment]
pip install AppKit

May also work.

**Comment by PaawanSharma** [comment]
Thanks for the reply. I'm using a Conda environment. Can I safely use pip without messing up my environment?

**Comment by PaawanSharma** [comment]
I tried downloading the source from https://github.com/nitipit/appkit and installing it using "python setup.py install" but I still get the same error when using prakriya.

**Comment by drdhaval2785** [comment]
In that case, you may try providing the path where you want the appdata to be stored manually at https://github.com/drdhaval2785/python-prakriya/blob/6694bbcce7e17a04fb89b89146c06df70e28e796/prakriya/utils.py#L35

**Comment by PaawanSharma** [comment]
Thanks. So do I need to uninstall prakriya, change that line and then reinstall?

**Comment by drdhaval2785** [comment]
No need to uninstall. You can locate the file utils.py in your system and make change in that file.

**Comment by PaawanSharma** [comment]
Thank you

**Comment by drdhaval2785** [comment]
Issue resolved Paawan ji?

**Comment by PaawanSharma** [comment]
Namaste,

I'm afraid not. I tried changing that line in utils.py but I still get the same error as before.

**Comment by PaawanSharma** [comment]
Any other suggestions for how to fix this, Dhaval ji?

**Comment by drdhaval2785** [comment]
I think your system is using the previously compiled binary.

**Comment by PaawanSharma** [comment]
> sudo pip install pyobjc

this fixed it. Thank you and sorry for the very late response!
